# Generated by Django 5.2 on 2026-04-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_poolconfiguration_signup_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolconfiguration',
            name='extra_prize_per_participants',
            field=models.PositiveIntegerField(default=2, verbose_name='prêmios extras a cada X participantes'),
        ),
        migrations.AddField(
            model_name='poolconfiguration',
            name='extra_prize_threshold',
            field=models.PositiveIntegerField(default=20, verbose_name='limite participantes prêmio extra'),
        ),
        migrations.AddField(
            model_name='poolconfiguration',
            name='extra_prize_value',
            field=models.PositiveIntegerField(default=30, verbose_name='valor prêmio extra'),
        ),
        migrations.AddField(
            model_name='poolconfiguration',
            name='quota_price',
            field=models.PositiveIntegerField(default=30, verbose_name='valor da cota'),
        ),
        migrations.AddField(
            model_name='poolconfiguration',
            name='stage1_first_percent',
            field=models.PositiveIntegerField(default=13, verbose_name='1º lugar 1ª fase %'),
        ),
        migrations.AddField(
            model_name='poolconfiguration',
            name='stage1_second_percent',
            field=models.PositiveIntegerField(default=10, verbose_name='2º lugar 1ª fase %'),
        ),
        migrations.AddField(
            model_name='poolconfiguration',
            name='stage1_third_percent',
            field=models.PositiveIntegerField(default=7, verbose_name='3º lugar 1ª fase %'),
        ),
        migrations.AddField(
            model_name='poolconfiguration',
            name='stage2_first_percent',
            field=models.PositiveIntegerField(default=34, verbose_name='1º lugar 2ª fase %'),
        ),
        migrations.AddField(
            model_name='poolconfiguration',
            name='stage2_second_percent',
            field=models.PositiveIntegerField(default=23, verbose_name='2º lugar 2ª fase %'),
        ),
        migrations.AddField(
            model_name='poolconfiguration',
            name='stage2_third_percent',
            field=models.PositiveIntegerField(default=13, verbose_name='3º lugar 2ª fase %'),
        ),
    ]
