# Generated by Django 5.2.13 on 2026-04-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='match',
            new_name='worldcup_ma_start_t_00983d_idx',
            old_name='worldcup_ma_start_t_5fb9f3_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='worldcup_ma_stage_i_f20f83_idx',
            old_name='worldcup_ma_stage_i_f2ad2a_idx',
        ),
    ]
