# Generated by Django 5.2 on 2026-04-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0002_rename_worldcup_ma_start_t_5fb9f3_idx_worldcup_ma_start_t_00983d_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['group', 'position', 'name'], 'verbose_name': 'seleção', 'verbose_name_plural': 'seleções'},
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='posição no grupo'),
        ),
    ]
