# Generated by Django 5.2 on 2026-04-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='stage1_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='stage1_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='stage2_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='stage2_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
